// Shared compliance / legal building blocks for GLP-1 Coach.
//
// Centralizes the configurable legal URLs and the bilingual (en/tr) disclaimer
// copy required for App Store review (Guideline 1.4.1 medical-harm disclaimers,
// AI-estimate accuracy, and data-sent-to-server transparency — report D3/D4).
//
// URLs are placeholders by default but can be overridden per-build via
// app config: app.json / app.config.js -> expo.extra. Example:
//
//   {
//     "expo": {
//       "extra": {
//         "supportUrl": "https://example.com/support",
//         "privacyUrl": "https://example.com/privacy",
//         "termsUrl":   "https://example.com/terms"
//       }
//     }
//   }
//
// Everything here is plain data so it can be imported from anywhere (screens,
// components, services) without pulling in React.

import Constants from 'expo-constants';

// expo-constants surfaces app config under expoConfig (SDK 46+) with a
// legacy `manifest` fallback. Guard every access so a missing field never throws.
const extra =
  (Constants &&
    ((Constants.expoConfig && Constants.expoConfig.extra) ||
      (Constants.manifest && Constants.manifest.extra))) ||
  {};

// Placeholder fallbacks — swap the real URLs in via expo.extra (above) at build
// time. Kept as obvious placeholders so they are easy to spot if shipped as-is.
const DEFAULTS = {
  supportUrl: 'https://example.com/glp1-coach/support',
  privacyUrl: 'https://example.com/glp1-coach/privacy',
  termsUrl: 'https://example.com/glp1-coach/terms',
};

export const SUPPORT_URL = extra.supportUrl || DEFAULTS.supportUrl;
export const PRIVACY_URL = extra.privacyUrl || DEFAULTS.privacyUrl;
export const TERMS_URL = extra.termsUrl || DEFAULTS.termsUrl;

// ---------------------------------------------------------------------------
// Bilingual disclaimer copy
// ---------------------------------------------------------------------------
// Each variant has a short `title` (good for a banner heading / inline label)
// and a longer `body` (full sentence for settings / consent screens).
//   - medical : not medical advice, consult a doctor
//   - ai      : AI estimates may be inaccurate
//   - data    : data is sent to a server for AI analysis
//
// Shape: DISCLAIMERS[variant][language] = { title, body }
export const DISCLAIMERS = {
  medical: {
    en: {
      title: 'Not medical advice',
      body:
        'GLP-1 Coach is for general informational and educational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult your doctor or a qualified healthcare provider before making any decisions about medication, diet, or your health.',
    },
    tr: {
      title: 'Tıbbi tavsiye değildir',
      body:
        'GLP-1 Coach yalnızca genel bilgilendirme ve eğitim amaçlıdır; profesyonel tıbbi tavsiye, teşhis veya tedavinin yerini tutmaz. İlaç, beslenme veya sağlığınızla ilgili herhangi bir karar vermeden önce mutlaka doktorunuza veya yetkili bir sağlık uzmanına danışın.',
    },
  },
  ai: {
    en: {
      title: 'AI estimates may be inaccurate',
      body:
        'Insights, scores, and suggestions are generated by AI and are estimates only. They may be incomplete or wrong. Do not rely on them for medical or safety-critical decisions — verify important information with a professional.',
    },
    tr: {
      title: 'Yapay zekâ tahminleri hatalı olabilir',
      body:
        'İçgörüler, puanlar ve öneriler yapay zekâ tarafından üretilir ve yalnızca tahmindir. Eksik veya yanlış olabilir. Tıbbi ya da güvenlik açısından kritik kararlarda bunlara güvenmeyin — önemli bilgileri bir uzmanla doğrulayın.',
    },
  },
  data: {
    en: {
      title: 'Data sent for AI analysis',
      body:
        'To generate AI insights, the information you enter (which may include health-related data) is sent to a server for processing. Avoid entering details you do not want to share. See our Privacy Policy for more.',
    },
    tr: {
      title: 'Veriler yapay zekâ analizi için gönderilir',
      body:
        'Yapay zekâ içgörüleri oluşturmak için girdiğiniz bilgiler (sağlıkla ilgili veriler içerebilir) işlenmek üzere bir sunucuya gönderilir. Paylaşmak istemediğiniz ayrıntıları girmeyin. Daha fazlası için Gizlilik Politikamıza bakın.',
    },
  },
};

// Convenience accessor: getDisclaimer('medical', 'tr') -> { title, body }
// Falls back to English, then to the medical variant, so callers always get
// a valid { title, body } object.
export function getDisclaimer(variant = 'medical', language = 'en') {
  const group = DISCLAIMERS[variant] || DISCLAIMERS.medical;
  return group[language] || group.en;
}

export default {
  SUPPORT_URL,
  PRIVACY_URL,
  TERMS_URL,
  DISCLAIMERS,
  getDisclaimer,
};
